sudo: required
dist: trusty
addons: 
  chrome: stable
  postgres: "9.6"
services:
  - postgresql
language: elixir
node_js: "7.7.2"
elixir:
    - 1.5.0
env:
  - NODE_VERSION="7.7.2" DISPLAY=":99.0"
before_install:
  - nvm install $NODE_VERSION
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - chromedriver --version
  - google-chrome --version
  - sudo service postgresql stop 9.2
  - sudo service postgresql start 9.6
  - createdb travis
  - psql -c "show server_version;"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - npm install -g brunch
  - cd assets
  - npm install
  - brunch build --production
  - cd .. && mix phx.digest
