version: 2
jobs:
  build:
    working_directory: ~/tilex
    docker:
      - image: circleci/elixir:1.7.4-node-browsers
      - image: postgres:9.6.5
        environment:
          POSTGRES_USER: postgres
          ASYNC_FEATURE_TEST: yes
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential
      - run: sudo apt-get install libnss3 libgconf-2-4
      - run: sudo apt-get install libxss1 libappindicator1 libindicator7
      - run: sudo apt-get install libasound2 libgtk-3-0 libxtst6 fonts-liberation lsb-release xdg-utils libappindicator3-1
      - run: sudo apt-get install -f
      - run: elixir -v
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: MIX_ENV=test mix ecto.create
      - run: MIX_ENV=test mix ecto.migrate
      - run: sudo npm install -g webpack
      - run: cd assets && npm install
      - run: cd assets && node node_modules/webpack/bin/webpack.js --mode production
      - run: mix phx.digest
      - run: mix format --check-formatted
      - run: mix test
      - run: mix credo
      - store_artifacts:
          path: /home/circleci/tilex/screenshots
